<a href="https://colab.research.google.com/github/filipesartori/Inteligencia-Artificial/blob/main/Algoritmos_de_Otimiza%C3%A7%C3%A3o_EXEMPLO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install mlrose

In [4]:
import mlrose

In [5]:
produtos = [('Refrigerador A', 0.751, 999.90),
            ('Celular', 0.0000899, 2911.12),
            ('TV 55', 0.400, 4346.99),
            ('TV 50', 0.290, 3999.90),
            ('TV 42', 0.200, 2999.00),
            ('Notebook A', 0.00350, 2499.90),
            ('Ventilador', 0.496, 199.90),
            ('Microondas A', 0.0424, 308.66),
            ('Microondas B', 0.0544, 429.90),
            ('Microondas C', 0.0319, 299.29),
            ('Refrigerador B', 0.635, 849.00),
            ('Refrigerador C', 0.870, 1199.89),
            ('Notebook B', 0.498, 1999.90),
            ('Notebook C', 0.527, 3999.00)]
espaco_disponivel = 3

In [6]:
def imprimir_solucao(solucao):
  for i in range(len(solucao)):
    if solucao[i] == 1:
      print('%s - %s' % (produtos[i][0], produtos[i][2]))

In [7]:
imprimir_solucao([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

Celular - 2911.12
TV 42 - 2999.0
Notebook A - 2499.9
Ventilador - 199.9
Microondas B - 429.9
Microondas C - 299.29
Refrigerador C - 1199.89
Notebook B - 1999.9
Notebook C - 3999.0


In [9]:
def fitness_function(solucao):
  custo = 0
  soma_espaco = 0
  for i in range(len(solucao)):
    if solucao[i] == 1:
      custo += produtos[i][2]
      soma_espaco += produtos[i][1]
  if soma_espaco > espaco_disponivel:
    custo = 1
  return custo      

In [10]:
fitness_function([0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1])

16537.9

In [11]:
fitness = mlrose.CustomFitness(fitness_function)

In [12]:
problema = mlrose.DiscreteOpt(length=14, fitness_fn=fitness, 
                              maximize = True, max_val = 2)

In [13]:
melhor_solucao, melhor_custo = mlrose.hill_climb(problema)
melhor_solucao, melhor_custo 

(array([1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]), 15846.56)

In [14]:
imprimir_solucao(melhor_solucao)

Refrigerador A - 999.9
Celular - 2911.12
TV 42 - 2999.0
Notebook A - 2499.9
Ventilador - 199.9
Microondas A - 308.66
Microondas B - 429.9
Microondas C - 299.29
Refrigerador C - 1199.89
Notebook C - 3999.0


In [15]:
melhor_solucao, melhor_custo = mlrose.simulated_annealing(problema)
melhor_solucao, melhor_custo

/usr/local/lib/python3.7/dist-packages/mlrose/algorithms.py:311: RuntimeWarning: overflow encountered in exp
  prob = np.exp(delta_e/temp)


(array([1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1]), 19295.67)

In [16]:
imprimir_solucao(melhor_solucao)

Refrigerador A - 999.9
Celular - 2911.12
TV 50 - 3999.9
TV 42 - 2999.0
Notebook A - 2499.9
Microondas A - 308.66
Microondas B - 429.9
Microondas C - 299.29
Refrigerador B - 849.0
Notebook C - 3999.0


In [17]:
melhor_solucao, melhor_custo = mlrose.genetic_alg(problema, pop_size=500, mutation_prob=0.2)
melhor_solucao, melhor_custo

(array([0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1]), 24993.550000000003)

In [18]:
imprimir_solucao(melhor_solucao)

Celular - 2911.12
TV 55 - 4346.99
TV 50 - 3999.9
TV 42 - 2999.0
Notebook A - 2499.9
Microondas A - 308.66
Microondas B - 429.9
Microondas C - 299.29
Refrigerador C - 1199.89
Notebook B - 1999.9
Notebook C - 3999.0
